#1. create User
###
POST http://localhost:5000/user
Content-Type: application/json

{
  "name": "Ujang Aripin",
  "email": "ujang@gmail.com",
  "password": "asd",
  "confPassword": "asd",
  "role": "admin"
}

#2. get user
###
GET http://localhost:5000/users

#3. get user by id
###
GET http://localhost:5000/user/b285de0f-1233-401d-b16c-b52c42d3b07d

#4. update user
###
PATCH http://localhost:5000/user/b285de0f-1233-401d-b16c-b52c42d3b07d
Content-Type: application/json

{
  "name": "Ujang Aripin",
  "email": "ujang@gmail.com",
  "password": "123456",
  "confPassword": "123456",
  "role": "admin"
}

#5. delete user
###
DELETE http://localhost:5000/user/b285de0f-1233-401d-b16c-b52c42d3b07d