#1. create User
###
POST http://localhost:5000/user
Content-Type: application/json

{
  "name": "Ujang Aripin",
  "email": "ujang@gmail.com",
  "password": "123456",
  "confPassword": "123456",
  "role": "admin"
}

#2. get user
###
GET http://localhost:5000/users

#3. get user by id
###
GET http://localhost:5000/user/0b170c5b-0530-4afc-bdb1-f58b2555ecbf

#4. update user
###
PATCH http://localhost:5000/user/0b170c5b-0530-4afc-bdb1-f58b2555ecbf
Content-Type: application/json

{
  "name": "James Hunt F1",
  "email": "james@gmail.com",
  "password": "123456",
  "confPassword": "123456",
  "role": "user"
}

#5. delete user
###
DELETE http://localhost:5000/user/0b170c5b-0530-4afc-bdb1-f58b2555ecbf

#6. login
###
POST http://localhost:5000/login
Accept: application/json
Content-Type: application/json

{
    "email": "ujang@Gmail.com",
    "password": "123456"
}

#7. status user
###
GET http://localhost:5000/status

#8. logout
###
DELETE http://localhost:5000/logout/

#9. get product
###
GET http://localhost:5000/product

#10. create product
###
POST http://localhost:5000/product
Accept: application/json
Content-Type: application/json

{
    "name": "product 2",
    "price": 200000
}

#11. get product by id
###
GET http://localhost:5000/product/7ce10179-93e5-442b-8d18-7ea3f4dc0c1b